Реализовать первый этап дипломного проекта - сервис статистики посеще…
Ersh0w/java-explore-with-me pull request #3
Opened 2023-09-02 12:18 UTC by Ersh0w

…ния эндпоинтов.

2023-09-03 06:00 UTC, sergeymamonov requested changes

2023-09-03 06:00 UTC, sergeymamonov commented on stats-service/service/src/main/java/ru/practicum/StatsService.java
> +        System.setProperty("server.port", "9091");
Лишнее. Попробуйте без этого сеттера.

2023-09-03 13:05 UTC, Ersh0w commented on stats-service/client/src/main/java/ru/practicum/StatsClientApp.java
> +public class StatsClientApp {
Сергей, возможно ли оставить такой вариант для масштабирования распределения нагрузки сбора статистики?

2023-09-04 18:23 UTC, Ersh0w commented on stats-service/client/src/main/java/ru/practicum/controller/StatsController.java
> +public class StatsController {
Исправлено.

2023-09-04 18:23 UTC, Ersh0w commented on stats-service/service/src/main/java/ru/practicum/StatsService.java
> +        System.setProperty("server.port", "9091");
Исправлено.

2023-09-04 19:52 UTC, sergeymamonov approved these changes

2023-09-04 19:52 UTC, sergeymamonov commented on stats-service/dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +public class EndpointHitDto {
В качестве улучшения можно сделать классы dto иммутабельными.

2023-09-06 11:38 UTC, merged