Реализовать второй этап дипломного проекта - сервис афиша интересных …
Ersh0w/java-explore-with-me pull request #4
Opened 2023-09-12 23:14 UTC by Ersh0w

…событий.

2023-09-13 16:08 UTC, sergeymamonov requested changes
Убрать по коду лишнее приведение к инту (встречается несколько раз в коде).

Если код метода не помещается на экран, то имеет смысл подумать о том, чтобы выделить в нем подметоды (если есть такая возможность).

2023-09-13 16:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +}
Лучше еще сделать обработку RuntimeException.

2023-09-13 16:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/user/UserControllerAdmin.java
> +        try {
Ошибки лучше перехватывать и обрабатывать в сервисе. И странно, почему этой ошибки нет в определении метода? Перехватывать нужно только проверяемые исключения. А для чего тогда нужен ErrorHandler. Подумайте над этими вопросами.

2023-09-13 22:43 UTC, Ersh0w commented on main-service/src/main/java/ru/practicum/category/dto/CategoryDto.java
> +public class CategoryDto {
Попробую реализовать если будет время до жесткого дедлайна.

2023-09-13 22:43 UTC, Ersh0w commented on main-service/src/main/java/ru/practicum/category/service/CategoryPublicServiceImpl.java
> +        Pageable pageable = PageRequest.of((int) (from / size), (int) size);
Исправлено.

2023-09-13 22:43 UTC, Ersh0w commented on main-service/src/main/java/ru/practicum/event/service/EventAdminServiceImpl.java
> +    public EventFullDto updateEvent(long eventId, UpdateEventAdminRequest updateEventAdminRequest) {
Исправлено.

2023-09-13 22:44 UTC, Ersh0w commented on main-service/src/main/java/ru/practicum/event/service/EventPublicService.java
> +    List<EventShortDto> getEvents(String text, List<Long> categories, Boolean paid, LocalDateTime rangeStart,
Исправлено.

2023-09-13 22:44 UTC, Ersh0w commented on main-service/src/main/java/ru/practicum/event/EventMapper.java
> +        //    if (event.getPublishedOn() != null) {
Исправлено.

2023-09-13 22:44 UTC, Ersh0w commented on main-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +}
Исправлено.

2023-09-13 22:44 UTC, Ersh0w commented on main-service/src/main/java/ru/practicum/user/UserControllerAdmin.java
> +        try {
Исправлено. Спасибо!

2023-09-14 04:07 UTC, sergeymamonov approved these changes

2023-09-14 04:07 UTC, sergeymamonov commented on main-service/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:6542/ewm-db
Удалить.

2023-09-14 04:07 UTC, sergeymamonov commented on stats-service/service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +    }
Аналогично, сделать обработку RuntimeException.

2023-09-14 10:52 UTC, merged